### ISSUE TITLE
Unbound variable error at  /api/v1/stories/meta/

### ISSUE THREAD

**Issue by ansal** [klpdotorg/dubdubdub#738]
```
Traceback (most recent call last):
  File "/home/ubuntu/dubdubdub/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/dubdubdub/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/dubdubdub/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/dubdubdub/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/dubdubdub/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/dubdubdub/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/dubdubdub/apps/stories/api_views.py", line 818, in get
    unique_schools_counts_per_source,
  File "/home/ubuntu/dubdubdub/apps/stories/api_views.py", line 913, in get_json
    json['schools'] = school_count
UnboundLocalError: local variable 'school_count' referenced before assignment
```

**Comment by prajdataspect** [comment]
I have made a change on my local machine. Is there a test case to check it's working?

**Comment by ansal** [comment]
@prajdataspect We dont have any test cases as of now. You have to test the endpoints manually.
